version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:3000"
    stdin_open: true
    tty: true
    command: yarn dev --host
